### ISSUE TITLE
Is !exists necessary for a create rule?

### ISSUE THREAD

**Issue by markulrich** [firebase/snippets-rules#1]
Thanks for the very helpful examples! For the step5.rules is
https://github.com/firebase/snippets-rules/blob/35476a30dc022f29d9c1d3df8cbd44c35a3f0f48/rules/solution-rbac/step5.rules#L17
an unnecessarily costly check because by definition create is already `!exist`?

If many users who have create but not update access are concurrently creating documents with the same path, is it possible for more than 1 of the requests to succeed?

**Comment by samtstern** [comment]
@markulrich first of all thanks for filing issue #1 on this repository!  It's officially a party now (I was here alone before and it was a little awkward).

Second of all you're completely right: when we moved from a `write` to a `create` rule we no longer need the `exists()` check.  Also I think we could just check `resource.data` rather than use the function at all even in the other case.  I will make some updates.
